// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm.swimlane;

import newlaw.bpm.swimlane.SwimlaneAssignment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SwimlaneAssignment_Roo_Configurable {
    
    declare @type: SwimlaneAssignment: @Configurable;
    
}
