// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm.keydate;

import newlaw.bpm.keydate.KeyDate;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect KeyDate_Roo_Configurable {
    
    declare @type: KeyDate: @Configurable;
    
}
