// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.bpm;

import nl24.bpm.Nl24SwimlaneAssignment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Nl24SwimlaneAssignment_Roo_Configurable {
    
    declare @type: Nl24SwimlaneAssignment: @Configurable;
    
}
