// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm.phase;

import newlaw.bpm.phase.PhaseAssignment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhaseAssignment_Roo_Configurable {
    
    declare @type: PhaseAssignment: @Configurable;
    
}
