// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.passenger;

import javax.persistence.Entity;
import nl24.passenger.Nl24PassengerProcessInstance;

privileged aspect Nl24PassengerProcessInstance_Roo_Jpa_Entity {
    
    declare @type: Nl24PassengerProcessInstance: @Entity;
    
}
