// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.passenger;

import nl24.passenger.Nl24PassengerProcessInstance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Nl24PassengerProcessInstance_Roo_Configurable {
    
    declare @type: Nl24PassengerProcessInstance: @Configurable;
    
}
