// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.passenger;

import javax.persistence.Entity;
import nl24.passenger.PassengerClaim;

privileged aspect PassengerClaim_Roo_Jpa_Entity {
    
    declare @type: PassengerClaim: @Entity;
    
}
