// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.propertychangetracker;

import newlaw.propertychangetracker.PropertyChange;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PropertyChange_Roo_Configurable {
    
    declare @type: PropertyChange: @Configurable;
    
}
