// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm;

import newlaw.bpm.ProcessData;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProcessData_Roo_Configurable {
    
    declare @type: ProcessData: @Configurable;
    
}
