// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm;

import newlaw.bpm.ProcessData;

privileged aspect ProcessData_Roo_JavaBean {
    
    public Long ProcessData.getId() {
        return this.id;
    }
    
    public void ProcessData.setId(Long id) {
        this.id = id;
    }
    
}
