//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AccidentTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="AccidentLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentCircumstances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPassengers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AccidentSeatBelt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AccidentWitnesses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AccidentRoadCond" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentWeatherCond" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentRoadType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentSpeedLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentTPSpeed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentVehicleSpeed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPoliceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPoliceNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPoliceStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPoliceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentPoliceWitness" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AccidentWarningGiven" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentTPWitness" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AccidentNoofVehicles" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="AccidentJourney" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentVisibility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentLightCond" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Referrer" type="{}ReferrerDetail"/>
 *         &lt;element name="AffinityCode" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="VehicleDriveable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="RepairingGarage" type="{}GarageDetail" minOccurs="0"/>
 *         &lt;element name="Client" type="{}ClientDetail"/>
 *         &lt;element name="ThirdParty" type="{}ThirdPartyDetail" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="Passenger" type="{}PassengerDetail" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="Witness" type="{}WitnessDetail" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="DriverAtTimeOfAccident" type="{}DriverAtTimeOfAccidentDetail" minOccurs="0"/>
 *         &lt;element name="AdditionalDriver" type="{}AdditionalDriverDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Repair" type="{}RepairDetail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "accidentDate",
    "accidentTime",
    "accidentLocation",
    "accidentCircumstances",
    "accidentPassengers",
    "accidentSeatBelt",
    "accidentWitnesses",
    "accidentRoadCond",
    "accidentWeatherCond",
    "accidentRoadType",
    "accidentSpeedLimit",
    "accidentTPSpeed",
    "accidentVehicleSpeed",
    "accidentPoliceName",
    "accidentPoliceNo",
    "accidentPoliceStation",
    "accidentPoliceRef",
    "accidentPoliceWitness",
    "accidentWarningGiven",
    "accidentTPWitness",
    "accidentNoofVehicles",
    "accidentJourney",
    "accidentVisibility",
    "accidentLightCond",
    "referrer",
    "affinityCode",
    "vehicleDriveable",
    "repairingGarage",
    "client",
    "thirdParty",
    "passenger",
    "witness",
    "driverAtTimeOfAccident",
    "additionalDriver",
    "repair"
})
@XmlRootElement(name = "Claim")
public class Claim {

    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "AccidentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accidentDate;
    @XmlElement(name = "AccidentTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar accidentTime;
    @XmlElement(name = "AccidentLocation")
    protected String accidentLocation;
    @XmlElement(name = "AccidentCircumstances")
    protected String accidentCircumstances;
    @XmlElement(name = "AccidentPassengers")
    protected Boolean accidentPassengers;
    @XmlElement(name = "AccidentSeatBelt")
    protected Boolean accidentSeatBelt;
    @XmlElement(name = "AccidentWitnesses")
    protected Boolean accidentWitnesses;
    @XmlElement(name = "AccidentRoadCond")
    protected String accidentRoadCond;
    @XmlElement(name = "AccidentWeatherCond")
    protected String accidentWeatherCond;
    @XmlElement(name = "AccidentRoadType")
    protected String accidentRoadType;
    @XmlElement(name = "AccidentSpeedLimit")
    protected String accidentSpeedLimit;
    @XmlElement(name = "AccidentTPSpeed")
    protected String accidentTPSpeed;
    @XmlElement(name = "AccidentVehicleSpeed")
    protected String accidentVehicleSpeed;
    @XmlElement(name = "AccidentPoliceName")
    protected String accidentPoliceName;
    @XmlElement(name = "AccidentPoliceNo")
    protected String accidentPoliceNo;
    @XmlElement(name = "AccidentPoliceStation")
    protected String accidentPoliceStation;
    @XmlElement(name = "AccidentPoliceRef")
    protected String accidentPoliceRef;
    @XmlElement(name = "AccidentPoliceWitness")
    protected Boolean accidentPoliceWitness;
    @XmlElement(name = "AccidentWarningGiven")
    protected String accidentWarningGiven;
    @XmlElement(name = "AccidentTPWitness")
    protected Boolean accidentTPWitness;
    @XmlElement(name = "AccidentNoofVehicles")
    protected BigInteger accidentNoofVehicles;
    @XmlElement(name = "AccidentJourney")
    protected String accidentJourney;
    @XmlElement(name = "AccidentVisibility")
    protected String accidentVisibility;
    @XmlElement(name = "AccidentLightCond")
    protected String accidentLightCond;
    @XmlElement(name = "Referrer", required = true)
    protected ReferrerDetail referrer;
    @XmlElement(name = "AffinityCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String affinityCode;
    @XmlElement(name = "VehicleDriveable")
    protected Boolean vehicleDriveable;
    @XmlElement(name = "RepairingGarage")
    protected GarageDetail repairingGarage;
    @XmlElement(name = "Client", required = true)
    protected ClientDetail client;
    @XmlElement(name = "ThirdParty")
    protected List<ThirdPartyDetail> thirdParty;
    @XmlElement(name = "Passenger")
    protected List<PassengerDetail> passenger;
    @XmlElement(name = "Witness")
    protected List<WitnessDetail> witness;
    @XmlElement(name = "DriverAtTimeOfAccident")
    protected DriverAtTimeOfAccidentDetail driverAtTimeOfAccident;
    @XmlElement(name = "AdditionalDriver")
    protected List<AdditionalDriverDetail> additionalDriver;
    @XmlElement(name = "Repair")
    protected RepairDetail repair;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the accidentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccidentDate() {
        return accidentDate;
    }

    /**
     * Sets the value of the accidentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccidentDate(XMLGregorianCalendar value) {
        this.accidentDate = value;
    }

    /**
     * Gets the value of the accidentTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccidentTime() {
        return accidentTime;
    }

    /**
     * Sets the value of the accidentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccidentTime(XMLGregorianCalendar value) {
        this.accidentTime = value;
    }

    /**
     * Gets the value of the accidentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentLocation() {
        return accidentLocation;
    }

    /**
     * Sets the value of the accidentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentLocation(String value) {
        this.accidentLocation = value;
    }

    /**
     * Gets the value of the accidentCircumstances property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentCircumstances() {
        return accidentCircumstances;
    }

    /**
     * Sets the value of the accidentCircumstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentCircumstances(String value) {
        this.accidentCircumstances = value;
    }

    /**
     * Gets the value of the accidentPassengers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccidentPassengers() {
        return accidentPassengers;
    }

    /**
     * Sets the value of the accidentPassengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccidentPassengers(Boolean value) {
        this.accidentPassengers = value;
    }

    /**
     * Gets the value of the accidentSeatBelt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccidentSeatBelt() {
        return accidentSeatBelt;
    }

    /**
     * Sets the value of the accidentSeatBelt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccidentSeatBelt(Boolean value) {
        this.accidentSeatBelt = value;
    }

    /**
     * Gets the value of the accidentWitnesses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccidentWitnesses() {
        return accidentWitnesses;
    }

    /**
     * Sets the value of the accidentWitnesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccidentWitnesses(Boolean value) {
        this.accidentWitnesses = value;
    }

    /**
     * Gets the value of the accidentRoadCond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentRoadCond() {
        return accidentRoadCond;
    }

    /**
     * Sets the value of the accidentRoadCond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentRoadCond(String value) {
        this.accidentRoadCond = value;
    }

    /**
     * Gets the value of the accidentWeatherCond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentWeatherCond() {
        return accidentWeatherCond;
    }

    /**
     * Sets the value of the accidentWeatherCond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentWeatherCond(String value) {
        this.accidentWeatherCond = value;
    }

    /**
     * Gets the value of the accidentRoadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentRoadType() {
        return accidentRoadType;
    }

    /**
     * Sets the value of the accidentRoadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentRoadType(String value) {
        this.accidentRoadType = value;
    }

    /**
     * Gets the value of the accidentSpeedLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentSpeedLimit() {
        return accidentSpeedLimit;
    }

    /**
     * Sets the value of the accidentSpeedLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentSpeedLimit(String value) {
        this.accidentSpeedLimit = value;
    }

    /**
     * Gets the value of the accidentTPSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentTPSpeed() {
        return accidentTPSpeed;
    }

    /**
     * Sets the value of the accidentTPSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentTPSpeed(String value) {
        this.accidentTPSpeed = value;
    }

    /**
     * Gets the value of the accidentVehicleSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentVehicleSpeed() {
        return accidentVehicleSpeed;
    }

    /**
     * Sets the value of the accidentVehicleSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentVehicleSpeed(String value) {
        this.accidentVehicleSpeed = value;
    }

    /**
     * Gets the value of the accidentPoliceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentPoliceName() {
        return accidentPoliceName;
    }

    /**
     * Sets the value of the accidentPoliceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentPoliceName(String value) {
        this.accidentPoliceName = value;
    }

    /**
     * Gets the value of the accidentPoliceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentPoliceNo() {
        return accidentPoliceNo;
    }

    /**
     * Sets the value of the accidentPoliceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentPoliceNo(String value) {
        this.accidentPoliceNo = value;
    }

    /**
     * Gets the value of the accidentPoliceStation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentPoliceStation() {
        return accidentPoliceStation;
    }

    /**
     * Sets the value of the accidentPoliceStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentPoliceStation(String value) {
        this.accidentPoliceStation = value;
    }

    /**
     * Gets the value of the accidentPoliceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentPoliceRef() {
        return accidentPoliceRef;
    }

    /**
     * Sets the value of the accidentPoliceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentPoliceRef(String value) {
        this.accidentPoliceRef = value;
    }

    /**
     * Gets the value of the accidentPoliceWitness property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccidentPoliceWitness() {
        return accidentPoliceWitness;
    }

    /**
     * Sets the value of the accidentPoliceWitness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccidentPoliceWitness(Boolean value) {
        this.accidentPoliceWitness = value;
    }

    /**
     * Gets the value of the accidentWarningGiven property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentWarningGiven() {
        return accidentWarningGiven;
    }

    /**
     * Sets the value of the accidentWarningGiven property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentWarningGiven(String value) {
        this.accidentWarningGiven = value;
    }

    /**
     * Gets the value of the accidentTPWitness property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccidentTPWitness() {
        return accidentTPWitness;
    }

    /**
     * Sets the value of the accidentTPWitness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccidentTPWitness(Boolean value) {
        this.accidentTPWitness = value;
    }

    /**
     * Gets the value of the accidentNoofVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccidentNoofVehicles() {
        return accidentNoofVehicles;
    }

    /**
     * Sets the value of the accidentNoofVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccidentNoofVehicles(BigInteger value) {
        this.accidentNoofVehicles = value;
    }

    /**
     * Gets the value of the accidentJourney property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentJourney() {
        return accidentJourney;
    }

    /**
     * Sets the value of the accidentJourney property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentJourney(String value) {
        this.accidentJourney = value;
    }

    /**
     * Gets the value of the accidentVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentVisibility() {
        return accidentVisibility;
    }

    /**
     * Sets the value of the accidentVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentVisibility(String value) {
        this.accidentVisibility = value;
    }

    /**
     * Gets the value of the accidentLightCond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentLightCond() {
        return accidentLightCond;
    }

    /**
     * Sets the value of the accidentLightCond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentLightCond(String value) {
        this.accidentLightCond = value;
    }

    /**
     * Gets the value of the referrer property.
     * 
     * @return
     *     possible object is
     *     {@link ReferrerDetail }
     *     
     */
    public ReferrerDetail getReferrer() {
        return referrer;
    }

    /**
     * Sets the value of the referrer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferrerDetail }
     *     
     */
    public void setReferrer(ReferrerDetail value) {
        this.referrer = value;
    }

    /**
     * Gets the value of the affinityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffinityCode() {
        return affinityCode;
    }

    /**
     * Sets the value of the affinityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffinityCode(String value) {
        this.affinityCode = value;
    }

    /**
     * Gets the value of the vehicleDriveable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVehicleDriveable() {
        return vehicleDriveable;
    }

    /**
     * Sets the value of the vehicleDriveable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVehicleDriveable(Boolean value) {
        this.vehicleDriveable = value;
    }

    /**
     * Gets the value of the repairingGarage property.
     * 
     * @return
     *     possible object is
     *     {@link GarageDetail }
     *     
     */
    public GarageDetail getRepairingGarage() {
        return repairingGarage;
    }

    /**
     * Sets the value of the repairingGarage property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarageDetail }
     *     
     */
    public void setRepairingGarage(GarageDetail value) {
        this.repairingGarage = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link ClientDetail }
     *     
     */
    public ClientDetail getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientDetail }
     *     
     */
    public void setClient(ClientDetail value) {
        this.client = value;
    }

    /**
     * Gets the value of the thirdParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thirdParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThirdParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThirdPartyDetail }
     * 
     * 
     */
    public List<ThirdPartyDetail> getThirdParty() {
        if (thirdParty == null) {
            thirdParty = new ArrayList<ThirdPartyDetail>();
        }
        return this.thirdParty;
    }

    /**
     * Gets the value of the passenger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passenger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassenger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassengerDetail }
     * 
     * 
     */
    public List<PassengerDetail> getPassenger() {
        if (passenger == null) {
            passenger = new ArrayList<PassengerDetail>();
        }
        return this.passenger;
    }

    /**
     * Gets the value of the witness property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the witness property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWitness().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WitnessDetail }
     * 
     * 
     */
    public List<WitnessDetail> getWitness() {
        if (witness == null) {
            witness = new ArrayList<WitnessDetail>();
        }
        return this.witness;
    }

    /**
     * Gets the value of the driverAtTimeOfAccident property.
     * 
     * @return
     *     possible object is
     *     {@link DriverAtTimeOfAccidentDetail }
     *     
     */
    public DriverAtTimeOfAccidentDetail getDriverAtTimeOfAccident() {
        return driverAtTimeOfAccident;
    }

    /**
     * Sets the value of the driverAtTimeOfAccident property.
     * 
     * @param value
     *     allowed object is
     *     {@link DriverAtTimeOfAccidentDetail }
     *     
     */
    public void setDriverAtTimeOfAccident(DriverAtTimeOfAccidentDetail value) {
        this.driverAtTimeOfAccident = value;
    }

    /**
     * Gets the value of the additionalDriver property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalDriver property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalDriver().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDriverDetail }
     * 
     * 
     */
    public List<AdditionalDriverDetail> getAdditionalDriver() {
        if (additionalDriver == null) {
            additionalDriver = new ArrayList<AdditionalDriverDetail>();
        }
        return this.additionalDriver;
    }

    /**
     * Gets the value of the repair property.
     * 
     * @return
     *     possible object is
     *     {@link RepairDetail }
     *     
     */
    public RepairDetail getRepair() {
        return repair;
    }

    /**
     * Sets the value of the repair property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepairDetail }
     *     
     */
    public void setRepair(RepairDetail value) {
        this.repair = value;
    }

}
