//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the driveassist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: driveassist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClientDetail }
     * 
     */
    public ClientDetail createClientDetail() {
        return new ClientDetail();
    }

    /**
     * Create an instance of {@link Claim }
     * 
     */
    public Claim createClaim() {
        return new Claim();
    }

    /**
     * Create an instance of {@link ReferrerDetail }
     * 
     */
    public ReferrerDetail createReferrerDetail() {
        return new ReferrerDetail();
    }

    /**
     * Create an instance of {@link GarageDetail }
     * 
     */
    public GarageDetail createGarageDetail() {
        return new GarageDetail();
    }

    /**
     * Create an instance of {@link ThirdPartyDetail }
     * 
     */
    public ThirdPartyDetail createThirdPartyDetail() {
        return new ThirdPartyDetail();
    }

    /**
     * Create an instance of {@link PassengerDetail }
     * 
     */
    public PassengerDetail createPassengerDetail() {
        return new PassengerDetail();
    }

    /**
     * Create an instance of {@link WitnessDetail }
     * 
     */
    public WitnessDetail createWitnessDetail() {
        return new WitnessDetail();
    }

    /**
     * Create an instance of {@link DriverAtTimeOfAccidentDetail }
     * 
     */
    public DriverAtTimeOfAccidentDetail createDriverAtTimeOfAccidentDetail() {
        return new DriverAtTimeOfAccidentDetail();
    }

    /**
     * Create an instance of {@link AdditionalDriverDetail }
     * 
     */
    public AdditionalDriverDetail createAdditionalDriverDetail() {
        return new AdditionalDriverDetail();
    }

    /**
     * Create an instance of {@link RepairDetail }
     * 
     */
    public RepairDetail createRepairDetail() {
        return new RepairDetail();
    }

    /**
     * Create an instance of {@link InsuranceDetail }
     * 
     */
    public InsuranceDetail createInsuranceDetail() {
        return new InsuranceDetail();
    }

    /**
     * Create an instance of {@link EngineerDetail }
     * 
     */
    public EngineerDetail createEngineerDetail() {
        return new EngineerDetail();
    }

    /**
     * Create an instance of {@link InsuranceExtraDetail }
     * 
     */
    public InsuranceExtraDetail createInsuranceExtraDetail() {
        return new InsuranceExtraDetail();
    }

    /**
     * Create an instance of {@link Insurer }
     * 
     */
    public Insurer createInsurer() {
        return new Insurer();
    }

    /**
     * Create an instance of {@link PersonDetail }
     * 
     */
    public PersonDetail createPersonDetail() {
        return new PersonDetail();
    }

    /**
     * Create an instance of {@link Broker }
     * 
     */
    public Broker createBroker() {
        return new Broker();
    }

    /**
     * Create an instance of {@link CompanyDetail }
     * 
     */
    public CompanyDetail createCompanyDetail() {
        return new CompanyDetail();
    }

    /**
     * Create an instance of {@link InjuryDetail }
     * 
     */
    public InjuryDetail createInjuryDetail() {
        return new InjuryDetail();
    }

    /**
     * Create an instance of {@link NetworkDetail }
     * 
     */
    public NetworkDetail createNetworkDetail() {
        return new NetworkDetail();
    }

    /**
     * Create an instance of {@link SolicitorDetail }
     * 
     */
    public SolicitorDetail createSolicitorDetail() {
        return new SolicitorDetail();
    }

    /**
     * Create an instance of {@link ClientDetail.VehicleDamage }
     * 
     */
    public ClientDetail.VehicleDamage createClientDetailVehicleDamage() {
        return new ClientDetail.VehicleDamage();
    }

}
