//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassengerDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengerDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}PersonDetail">
 *       &lt;sequence>
 *         &lt;element name="Solicitor" type="{}SolicitorDetail" minOccurs="0"/>
 *         &lt;element name="SawAccident" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="WearingSeatBelt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="HealthInsurance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PassengerNumber" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerDetail", propOrder = {
    "solicitor",
    "sawAccident",
    "wearingSeatBelt",
    "healthInsurance"
})
public class PassengerDetail
    extends PersonDetail
{

    @XmlElement(name = "Solicitor")
    protected SolicitorDetail solicitor;
    @XmlElement(name = "SawAccident")
    protected Boolean sawAccident;
    @XmlElement(name = "WearingSeatBelt")
    protected Boolean wearingSeatBelt;
    @XmlElement(name = "HealthInsurance")
    protected Boolean healthInsurance;
    @XmlAttribute(name = "PassengerNumber", required = true)
    protected int passengerNumber;

    /**
     * Gets the value of the solicitor property.
     * 
     * @return
     *     possible object is
     *     {@link SolicitorDetail }
     *     
     */
    public SolicitorDetail getSolicitor() {
        return solicitor;
    }

    /**
     * Sets the value of the solicitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolicitorDetail }
     *     
     */
    public void setSolicitor(SolicitorDetail value) {
        this.solicitor = value;
    }

    /**
     * Gets the value of the sawAccident property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSawAccident() {
        return sawAccident;
    }

    /**
     * Sets the value of the sawAccident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSawAccident(Boolean value) {
        this.sawAccident = value;
    }

    /**
     * Gets the value of the wearingSeatBelt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWearingSeatBelt() {
        return wearingSeatBelt;
    }

    /**
     * Sets the value of the wearingSeatBelt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWearingSeatBelt(Boolean value) {
        this.wearingSeatBelt = value;
    }

    /**
     * Gets the value of the healthInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHealthInsurance() {
        return healthInsurance;
    }

    /**
     * Sets the value of the healthInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHealthInsurance(Boolean value) {
        this.healthInsurance = value;
    }

    /**
     * Gets the value of the passengerNumber property.
     * 
     */
    public int getPassengerNumber() {
        return passengerNumber;
    }

    /**
     * Sets the value of the passengerNumber property.
     * 
     */
    public void setPassengerNumber(int value) {
        this.passengerNumber = value;
    }

}
