//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ReferrerDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferrerDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}CompanyDetail">
 *       &lt;sequence>
 *         &lt;element name="ReferrerReference" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ReferrerFaxback" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReferrerScheme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferrerDetail", propOrder = {
    "referrerReference",
    "referrerFaxback",
    "referrerScheme"
})
public class ReferrerDetail
    extends CompanyDetail
{

    @XmlElement(name = "ReferrerReference")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String referrerReference;
    @XmlElement(name = "ReferrerFaxback")
    protected Boolean referrerFaxback;
    @XmlElement(name = "ReferrerScheme")
    protected String referrerScheme;

    /**
     * Gets the value of the referrerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferrerReference() {
        return referrerReference;
    }

    /**
     * Sets the value of the referrerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferrerReference(String value) {
        this.referrerReference = value;
    }

    /**
     * Gets the value of the referrerFaxback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReferrerFaxback() {
        return referrerFaxback;
    }

    /**
     * Sets the value of the referrerFaxback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferrerFaxback(Boolean value) {
        this.referrerFaxback = value;
    }

    /**
     * Gets the value of the referrerScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferrerScheme() {
        return referrerScheme;
    }

    /**
     * Sets the value of the referrerScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferrerScheme(String value) {
        this.referrerScheme = value;
    }

}
