//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SolicitorDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolicitorDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}CompanyDetail">
 *       &lt;sequence>
 *         &lt;element name="DateAppointed" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DateConfirmed" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AppointedBy" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="CaseReference" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolicitorDetail", propOrder = {
    "dateAppointed",
    "dateConfirmed",
    "appointedBy",
    "caseReference"
})
public class SolicitorDetail
    extends CompanyDetail
{

    @XmlElement(name = "DateAppointed")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateAppointed;
    @XmlElement(name = "DateConfirmed")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateConfirmed;
    @XmlElement(name = "AppointedBy")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String appointedBy;
    @XmlElement(name = "CaseReference")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String caseReference;

    /**
     * Gets the value of the dateAppointed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAppointed() {
        return dateAppointed;
    }

    /**
     * Sets the value of the dateAppointed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAppointed(XMLGregorianCalendar value) {
        this.dateAppointed = value;
    }

    /**
     * Gets the value of the dateConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateConfirmed() {
        return dateConfirmed;
    }

    /**
     * Sets the value of the dateConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateConfirmed(XMLGregorianCalendar value) {
        this.dateConfirmed = value;
    }

    /**
     * Gets the value of the appointedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointedBy() {
        return appointedBy;
    }

    /**
     * Sets the value of the appointedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointedBy(String value) {
        this.appointedBy = value;
    }

    /**
     * Gets the value of the caseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseReference() {
        return caseReference;
    }

    /**
     * Sets the value of the caseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseReference(String value) {
        this.caseReference = value;
    }

}
