//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ThirdPartyDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThirdPartyDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}PersonDetail">
 *       &lt;sequence>
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TestPass" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Insurance" type="{}InsuranceDetail" minOccurs="0"/>
 *         &lt;element name="Solicitor" type="{}SolicitorDetail" minOccurs="0"/>
 *         &lt;element name="AdmitsLiability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="VehicleReg" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="VehicleMake" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="VehicleModel" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="VehicleDoors" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="VehicleType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="VehicleColour" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="VehicleDamage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommentsAtSceneOfAccident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Passenger" type="{}PassengerDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ThirdPartyNumber" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThirdPartyDetail", propOrder = {
    "dateOfBirth",
    "testPass",
    "insurance",
    "solicitor",
    "admitsLiability",
    "vehicleReg",
    "vehicleMake",
    "vehicleModel",
    "vehicleDoors",
    "vehicleType",
    "vehicleColour",
    "vehicleDamage",
    "commentsAtSceneOfAccident",
    "passenger"
})
public class ThirdPartyDetail
    extends PersonDetail
{

    @XmlElement(name = "DateOfBirth")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(name = "TestPass")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar testPass;
    @XmlElement(name = "Insurance")
    protected InsuranceDetail insurance;
    @XmlElement(name = "Solicitor")
    protected SolicitorDetail solicitor;
    @XmlElement(name = "AdmitsLiability")
    protected Boolean admitsLiability;
    @XmlElement(name = "VehicleReg")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String vehicleReg;
    @XmlElement(name = "VehicleMake")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleMake;
    @XmlElement(name = "VehicleModel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleModel;
    @XmlElement(name = "VehicleDoors")
    protected BigInteger vehicleDoors;
    @XmlElement(name = "VehicleType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleType;
    @XmlElement(name = "VehicleColour")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleColour;
    @XmlElement(name = "VehicleDamage")
    protected String vehicleDamage;
    @XmlElement(name = "CommentsAtSceneOfAccident")
    protected String commentsAtSceneOfAccident;
    @XmlElement(name = "Passenger")
    protected List<PassengerDetail> passenger;
    @XmlAttribute(name = "ThirdPartyNumber", required = true)
    protected int thirdPartyNumber;

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the testPass property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestPass() {
        return testPass;
    }

    /**
     * Sets the value of the testPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestPass(XMLGregorianCalendar value) {
        this.testPass = value;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceDetail }
     *     
     */
    public InsuranceDetail getInsurance() {
        return insurance;
    }

    /**
     * Sets the value of the insurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceDetail }
     *     
     */
    public void setInsurance(InsuranceDetail value) {
        this.insurance = value;
    }

    /**
     * Gets the value of the solicitor property.
     * 
     * @return
     *     possible object is
     *     {@link SolicitorDetail }
     *     
     */
    public SolicitorDetail getSolicitor() {
        return solicitor;
    }

    /**
     * Sets the value of the solicitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolicitorDetail }
     *     
     */
    public void setSolicitor(SolicitorDetail value) {
        this.solicitor = value;
    }

    /**
     * Gets the value of the admitsLiability property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdmitsLiability() {
        return admitsLiability;
    }

    /**
     * Sets the value of the admitsLiability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdmitsLiability(Boolean value) {
        this.admitsLiability = value;
    }

    /**
     * Gets the value of the vehicleReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleReg() {
        return vehicleReg;
    }

    /**
     * Sets the value of the vehicleReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleReg(String value) {
        this.vehicleReg = value;
    }

    /**
     * Gets the value of the vehicleMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMake() {
        return vehicleMake;
    }

    /**
     * Sets the value of the vehicleMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMake(String value) {
        this.vehicleMake = value;
    }

    /**
     * Gets the value of the vehicleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * Sets the value of the vehicleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleModel(String value) {
        this.vehicleModel = value;
    }

    /**
     * Gets the value of the vehicleDoors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVehicleDoors() {
        return vehicleDoors;
    }

    /**
     * Sets the value of the vehicleDoors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVehicleDoors(BigInteger value) {
        this.vehicleDoors = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the vehicleColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleColour() {
        return vehicleColour;
    }

    /**
     * Sets the value of the vehicleColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleColour(String value) {
        this.vehicleColour = value;
    }

    /**
     * Gets the value of the vehicleDamage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleDamage() {
        return vehicleDamage;
    }

    /**
     * Sets the value of the vehicleDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleDamage(String value) {
        this.vehicleDamage = value;
    }

    /**
     * Gets the value of the commentsAtSceneOfAccident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentsAtSceneOfAccident() {
        return commentsAtSceneOfAccident;
    }

    /**
     * Sets the value of the commentsAtSceneOfAccident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentsAtSceneOfAccident(String value) {
        this.commentsAtSceneOfAccident = value;
    }

    /**
     * Gets the value of the passenger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passenger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassenger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassengerDetail }
     * 
     * 
     */
    public List<PassengerDetail> getPassenger() {
        if (passenger == null) {
            passenger = new ArrayList<PassengerDetail>();
        }
        return this.passenger;
    }

    /**
     * Gets the value of the thirdPartyNumber property.
     * 
     */
    public int getThirdPartyNumber() {
        return thirdPartyNumber;
    }

    /**
     * Sets the value of the thirdPartyNumber property.
     * 
     */
    public void setThirdPartyNumber(int value) {
        this.thirdPartyNumber = value;
    }

}
