//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.13 at 09:47:59 AM BST 
//


package uk.co.driveassist;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for WitnessDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WitnessDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}PersonDetail">
 *       &lt;sequence>
 *         &lt;element name="SawAccident" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SawAccidentClearly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CommentsAtScene" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartiesKnown" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="WeatherCondition" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="RoadCondition" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ClientSpeed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ThirdPartySpeed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="VehicleWSOR" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ActionToAvoid" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ClientColl" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ThirdPartyColl" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Responsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdmitResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccidentDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="WitnessNumber" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WitnessDetail", propOrder = {
    "sawAccident",
    "sawAccidentClearly",
    "commentsAtScene",
    "partiesKnown",
    "weatherCondition",
    "roadCondition",
    "clientSpeed",
    "thirdPartySpeed",
    "vehicleWSOR",
    "actionToAvoid",
    "clientColl",
    "thirdPartyColl",
    "responsible",
    "admitResponsible",
    "accidentDetails"
})
public class WitnessDetail
    extends PersonDetail
{

    @XmlElement(name = "SawAccident")
    protected Boolean sawAccident;
    @XmlElement(name = "SawAccidentClearly")
    protected Boolean sawAccidentClearly;
    @XmlElement(name = "CommentsAtScene")
    protected String commentsAtScene;
    @XmlElement(name = "PartiesKnown")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String partiesKnown;
    @XmlElement(name = "WeatherCondition")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String weatherCondition;
    @XmlElement(name = "RoadCondition")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String roadCondition;
    @XmlElement(name = "ClientSpeed")
    protected BigInteger clientSpeed;
    @XmlElement(name = "ThirdPartySpeed")
    protected BigInteger thirdPartySpeed;
    @XmlElement(name = "VehicleWSOR")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleWSOR;
    @XmlElement(name = "ActionToAvoid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String actionToAvoid;
    @XmlElement(name = "ClientColl")
    protected BigInteger clientColl;
    @XmlElement(name = "ThirdPartyColl")
    protected BigInteger thirdPartyColl;
    @XmlElement(name = "Responsible")
    protected String responsible;
    @XmlElement(name = "AdmitResponsible")
    protected String admitResponsible;
    @XmlElement(name = "AccidentDetails")
    protected String accidentDetails;
    @XmlAttribute(name = "WitnessNumber", required = true)
    protected int witnessNumber;

    /**
     * Gets the value of the sawAccident property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSawAccident() {
        return sawAccident;
    }

    /**
     * Sets the value of the sawAccident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSawAccident(Boolean value) {
        this.sawAccident = value;
    }

    /**
     * Gets the value of the sawAccidentClearly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSawAccidentClearly() {
        return sawAccidentClearly;
    }

    /**
     * Sets the value of the sawAccidentClearly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSawAccidentClearly(Boolean value) {
        this.sawAccidentClearly = value;
    }

    /**
     * Gets the value of the commentsAtScene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentsAtScene() {
        return commentsAtScene;
    }

    /**
     * Sets the value of the commentsAtScene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentsAtScene(String value) {
        this.commentsAtScene = value;
    }

    /**
     * Gets the value of the partiesKnown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartiesKnown() {
        return partiesKnown;
    }

    /**
     * Sets the value of the partiesKnown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartiesKnown(String value) {
        this.partiesKnown = value;
    }

    /**
     * Gets the value of the weatherCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeatherCondition() {
        return weatherCondition;
    }

    /**
     * Sets the value of the weatherCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeatherCondition(String value) {
        this.weatherCondition = value;
    }

    /**
     * Gets the value of the roadCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadCondition() {
        return roadCondition;
    }

    /**
     * Sets the value of the roadCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadCondition(String value) {
        this.roadCondition = value;
    }

    /**
     * Gets the value of the clientSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClientSpeed() {
        return clientSpeed;
    }

    /**
     * Sets the value of the clientSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClientSpeed(BigInteger value) {
        this.clientSpeed = value;
    }

    /**
     * Gets the value of the thirdPartySpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThirdPartySpeed() {
        return thirdPartySpeed;
    }

    /**
     * Sets the value of the thirdPartySpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThirdPartySpeed(BigInteger value) {
        this.thirdPartySpeed = value;
    }

    /**
     * Gets the value of the vehicleWSOR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleWSOR() {
        return vehicleWSOR;
    }

    /**
     * Sets the value of the vehicleWSOR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleWSOR(String value) {
        this.vehicleWSOR = value;
    }

    /**
     * Gets the value of the actionToAvoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionToAvoid() {
        return actionToAvoid;
    }

    /**
     * Sets the value of the actionToAvoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionToAvoid(String value) {
        this.actionToAvoid = value;
    }

    /**
     * Gets the value of the clientColl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClientColl() {
        return clientColl;
    }

    /**
     * Sets the value of the clientColl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClientColl(BigInteger value) {
        this.clientColl = value;
    }

    /**
     * Gets the value of the thirdPartyColl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThirdPartyColl() {
        return thirdPartyColl;
    }

    /**
     * Sets the value of the thirdPartyColl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThirdPartyColl(BigInteger value) {
        this.thirdPartyColl = value;
    }

    /**
     * Gets the value of the responsible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsible() {
        return responsible;
    }

    /**
     * Sets the value of the responsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsible(String value) {
        this.responsible = value;
    }

    /**
     * Gets the value of the admitResponsible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmitResponsible() {
        return admitResponsible;
    }

    /**
     * Sets the value of the admitResponsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmitResponsible(String value) {
        this.admitResponsible = value;
    }

    /**
     * Gets the value of the accidentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentDetails() {
        return accidentDetails;
    }

    /**
     * Sets the value of the accidentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentDetails(String value) {
        this.accidentDetails = value;
    }

    /**
     * Gets the value of the witnessNumber property.
     * 
     */
    public int getWitnessNumber() {
        return witnessNumber;
    }

    /**
     * Sets the value of the witnessNumber property.
     * 
     */
    public void setWitnessNumber(int value) {
        this.witnessNumber = value;
    }

}
