// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.bpm.attachment;

import newlaw.bpm.attachment.Attachment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Attachment_Roo_Configurable {
    
    declare @type: Attachment: @Configurable;
    
}
