// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.dap;

import newlaw.dap.DapKeyDate;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DapKeyDate_Roo_Configurable {
    
    declare @type: DapKeyDate: @Configurable;
    
}
