// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package newlaw.dap;

import newlaw.dap.DapProcessInstance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DapProcessInstance_Roo_Configurable {
    
    declare @type: DapProcessInstance: @Configurable;
    
}
