// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nl24.domain.CreditServiceProviderInstruction;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CreditServiceProviderInstruction_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager CreditServiceProviderInstruction.entityManager;
    
    public static final EntityManager CreditServiceProviderInstruction.entityManager() {
        EntityManager em = new CreditServiceProviderInstruction().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long CreditServiceProviderInstruction.countCreditServiceProviderInstructions() {
        return entityManager().createQuery("SELECT COUNT(o) FROM CreditServiceProviderInstruction o", Long.class).getSingleResult();
    }
    
    public static List<CreditServiceProviderInstruction> CreditServiceProviderInstruction.findAllCreditServiceProviderInstructions() {
        return entityManager().createQuery("SELECT o FROM CreditServiceProviderInstruction o", CreditServiceProviderInstruction.class).getResultList();
    }
    
    public static CreditServiceProviderInstruction CreditServiceProviderInstruction.findCreditServiceProviderInstruction(Long id) {
        if (id == null) return null;
        return entityManager().find(CreditServiceProviderInstruction.class, id);
    }
    
    public static List<CreditServiceProviderInstruction> CreditServiceProviderInstruction.findCreditServiceProviderInstructionEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM CreditServiceProviderInstruction o", CreditServiceProviderInstruction.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void CreditServiceProviderInstruction.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void CreditServiceProviderInstruction.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            CreditServiceProviderInstruction attached = CreditServiceProviderInstruction.findCreditServiceProviderInstruction(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void CreditServiceProviderInstruction.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void CreditServiceProviderInstruction.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public CreditServiceProviderInstruction CreditServiceProviderInstruction.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        CreditServiceProviderInstruction merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
