// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nl24.domain.Nl24Person;

privileged aspect Nl24Person_Roo_Jpa_Entity {
    
    declare @type: Nl24Person: @Entity;
    
    declare @type: Nl24Person: @Table(schema = "nl24", name = "person");
    
}
