// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import nl24.domain.PoliceAttendance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PoliceAttendance_Roo_Configurable {
    
    declare @type: PoliceAttendance: @Configurable;
    
}
