// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import nl24.domain.RecoveryAgent;
import nl24.domain.RecoveryAgentInstruction;

privileged aspect RecoveryAgentInstruction_Roo_JavaBean {
    
    public RecoveryAgent RecoveryAgentInstruction.getRecoveryAgent() {
        return this.recoveryAgent;
    }
    
    public void RecoveryAgentInstruction.setRecoveryAgent(RecoveryAgent recoveryAgent) {
        this.recoveryAgent = recoveryAgent;
    }
    
    public String RecoveryAgentInstruction.getVehicleLocation() {
        return this.vehicleLocation;
    }
    
    public void RecoveryAgentInstruction.setVehicleLocation(String vehicleLocation) {
        this.vehicleLocation = vehicleLocation;
    }
    
}
