// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import java.util.List;
import nl24.domain.RecoveryAgent;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecoveryAgent_Roo_Jpa_ActiveRecord {
    
    public static long RecoveryAgent.countRecoveryAgents() {
        return entityManager().createQuery("SELECT COUNT(o) FROM RecoveryAgent o", Long.class).getSingleResult();
    }
    
    public static List<RecoveryAgent> RecoveryAgent.findAllRecoveryAgents() {
        return entityManager().createQuery("SELECT o FROM RecoveryAgent o", RecoveryAgent.class).getResultList();
    }
    
    public static RecoveryAgent RecoveryAgent.findRecoveryAgent(Long id) {
        if (id == null) return null;
        return entityManager().find(RecoveryAgent.class, id);
    }
    
    public static List<RecoveryAgent> RecoveryAgent.findRecoveryAgentEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM RecoveryAgent o", RecoveryAgent.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public RecoveryAgent RecoveryAgent.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        RecoveryAgent merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
