// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import nl24.domain.RecoveryAgentInstruction;

privileged aspect RecoveryAgentInstruction_Roo_Jpa_Entity {
    
    declare @type: RecoveryAgentInstruction: @Entity;
    
    declare @type: RecoveryAgentInstruction: @Table(schema = "nl24");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long RecoveryAgentInstruction.id;
    
    @Version
    @Column(name = "version")
    private Integer RecoveryAgentInstruction.version;
    
    public Long RecoveryAgentInstruction.getId() {
        return this.id;
    }
    
    public void RecoveryAgentInstruction.setId(Long id) {
        this.id = id;
    }
    
    public Integer RecoveryAgentInstruction.getVersion() {
        return this.version;
    }
    
    public void RecoveryAgentInstruction.setVersion(Integer version) {
        this.version = version;
    }
    
}
