// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nl24.domain.RecoveryAgent;

privileged aspect RecoveryAgent_Roo_Jpa_Entity {
    
    declare @type: RecoveryAgent: @Entity;
    
    declare @type: RecoveryAgent: @Table(schema = "nl24");
    
}
