// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nl24.domain.RecoveryAgentInstruction;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecoveryAgentInstruction_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager RecoveryAgentInstruction.entityManager;
    
    public static final EntityManager RecoveryAgentInstruction.entityManager() {
        EntityManager em = new RecoveryAgentInstruction().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long RecoveryAgentInstruction.countRecoveryAgentInstructions() {
        return entityManager().createQuery("SELECT COUNT(o) FROM RecoveryAgentInstruction o", Long.class).getSingleResult();
    }
    
    public static List<RecoveryAgentInstruction> RecoveryAgentInstruction.findAllRecoveryAgentInstructions() {
        return entityManager().createQuery("SELECT o FROM RecoveryAgentInstruction o", RecoveryAgentInstruction.class).getResultList();
    }
    
    public static RecoveryAgentInstruction RecoveryAgentInstruction.findRecoveryAgentInstruction(Long id) {
        if (id == null) return null;
        return entityManager().find(RecoveryAgentInstruction.class, id);
    }
    
    public static List<RecoveryAgentInstruction> RecoveryAgentInstruction.findRecoveryAgentInstructionEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM RecoveryAgentInstruction o", RecoveryAgentInstruction.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void RecoveryAgentInstruction.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void RecoveryAgentInstruction.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            RecoveryAgentInstruction attached = RecoveryAgentInstruction.findRecoveryAgentInstruction(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void RecoveryAgentInstruction.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void RecoveryAgentInstruction.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public RecoveryAgentInstruction RecoveryAgentInstruction.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        RecoveryAgentInstruction merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
