// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.domain;

import nl24.domain.SolicitorInstruction;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SolicitorInstruction_Roo_Configurable {
    
    declare @type: SolicitorInstruction: @Configurable;
    
}
