// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl24.report;

import nl24.report.Nl24ReportService;

privileged aspect Nl24ReportService_Roo_JavaBean {
    
    public String Nl24ReportService.getKeyDatesBetweenDatesByBrokerQuery() {
        return this.keyDatesBetweenDatesByBrokerQuery;
    }
    
    public void Nl24ReportService.setKeyDatesBetweenDatesByBrokerQuery(String keyDatesBetweenDatesByBrokerQuery) {
        this.keyDatesBetweenDatesByBrokerQuery = keyDatesBetweenDatesByBrokerQuery;
    }
    
}
